name: kustomize

on:
  push:
    paths:
      - '.github/workflows/kustomize.yml'
      - 'build/kustomize/**'
      - '!build/kustomize/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Prepare
        id: prep
        run: |
          BASE_DIR=build/kustomize
          VERSION=$(cat ${BASE_DIR}/.version)
          # .version is "v3.3.1" for older versions, but "kustomize/v3.8.2" for newer ones
          # strip everything before the slash for the docker tag to be able to work with both
          DOCKER_TAG=$(sed 's|.*/||' < ${BASE_DIR}/.version)

          echo ::set-output name=version::${VERSION}
          echo ::set-output name=base_dir::${BASE_DIR}
          echo ::set-output name=docker_tag::${DOCKER_TAG}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          version: latest
          driver-opts: image=moby/buildkit:master

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push
        if: github.ref != 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          build-args: VERSION=${{ steps.prep.outputs.version }}
          context: ${{ steps.prep.outputs.base_dir }}/
          file: ${{ steps.prep.outputs.base_dir }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            raspbernetes/kustomize:${{ github.sha }}

      - name: Build and Push
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          build-args: VERSION=${{ steps.prep.outputs.version }}
          context: ${{ steps.prep.outputs.base_dir }}/
          file: ${{ steps.prep.outputs.base_dir }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            raspbernetes/kustomize:latest
            raspbernetes/kustomize:${{ steps.prep.outputs.docker_tag }}
